<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<?php
include_once('../config/symbini.php');
include_once($serverRoot.'/classes/DynamicChecklistManager.php');
header("Content-Type: text/html; charset=".$charset);

$tid = array_key_exists("tid",$_REQUEST)?$_REQUEST["tid"]:0;
$interface = array_key_exists("interface",$_REQUEST)&&$_REQUEST["interface"]?$_REQUEST["interface"]:"checklist";

$dynClManager = new DynamicChecklistManager();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo $defaultTitle; ?> - Dynamic Checklist Generator</title>
	<link rel="stylesheet" href="../css/main.css" type="text/css" />
	<script type="text/javascript">
	    //<![CDATA[
	    
	  	var zoomLevel = 5;
	  	var submitCoord = false;
	  	
	    function initialize(){
	
	        var map = new GMap2(document.getElementById("map"));
            <?php
				$latCen = 41.0;
				$longCen = -95.0;
				$coorArr = explode(";",$mappingBoundaries);
				if($coorArr && count($coorArr) == 4){
					$latCen = ($coorArr[0] + $coorArr[2])/2;
					$longCen = ($coorArr[1] + $coorArr[3])/2;
				}
				$coordRange = ($coorArr[0] - $coorArr[2]);
				$zoomInt = 5;
				if($coordRange < 20){
					$zoomInt = 6;
				}
				elseif($coordRange > 35 && $coordRange < 40){
					$zoomInt = 4;
				}
				elseif($coordRange > 40){
					$zoomInt = 3;
				}
			?>
			zoomLevel = <?php echo $zoomInt; ?>;
			map.setCenter(new GLatLng( <?php echo $latCen.",".$longCen; ?> ), zoomLevel);
	        map.setUIToDefault();
	        
	        GEvent.addListener(map, 'dblclick', function(overlay, point) {
				map.clearOverlays();
				map.zoomIn(point,true);
	        });
	
	        GEvent.addListener(map, 'click', function(overlay, point) {
				if(point) {
					map.clearOverlays();
	                var marker = new GMarker(point);
	                map.addOverlay(marker);
	                
					// Add Coords by clicking the map
			        var latValue = point.y;
			        var lonValue = point.x;
			        latValue = latValue.toFixed(5);;
			        lonValue = lonValue.toFixed(5);
					document.getElementById("latbox").value = latValue;
	                document.getElementById("lngbox").value = lonValue;
	                document.getElementById("latlngspan").innerHTML = latValue + ", " + lonValue;
	                submitCoord = true;
	         	}
	        });
	    }
	
	    function updateRadius(){
	    	var radiusUnits = document.getElementById("radiusunits").value;
	    	var radiusValue = document.getElementById("radiustemp").value;
	    	if(radiusUnits == "km"){
	    		radiusValue = radiusValue*0.6214; 
	    	}
	    	document.getElementById("radius").value = radiusValue;
	     }

		function checkForm(){
			if(submitCoord) return true;
			alert("You must first click on map to capture coordinate points");
			return false;
		}
	    //]]>
	</script>
	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', '<?php echo $googleAnalyticsKey; ?>']);
		_gaq.push(['_trackPageview']);
	
		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>
</head> 
<body onload="initialize()"  onunload="GUnload()">
    <script src="http://maps.google.com/maps?file=api&v=2&key=<?php echo $googleMapKey; ?>" type="text/javascript"></script>
	<?php 
		$displayLeftMenu = false;
		$displayStyle = "nostrip";
		include($serverRoot.'/header.php');
	?>
	    <div>
	    	Pan, zoom and click on map to capture coordinates. Once done, submit coordinates to build key. 
			<span style="cursor:pointer;color:blue;font-size:80%;" onclick="this.style.display='none';document.getElementById('moreinfo').style.display='block'">
				More Details
			</span>
	    </div>
		<div id="moreinfo" style="display:none;">
			Upon submitting coordinates, a species list will be generated by looking at all specimens collected near the submitted coordinates. 
			The area is sampled in concentric rings expanding from point until the sample size significantly represents the species diversity. 
			In other words, if an area has been poorly collected, a greater radius will be sampled.     
		</div>
		
	    <div style="margin-top:5px;">
			<form id="mapForm" action="dynamicchecklist.php" method="get" onsubmit="return checkForm();">
				<div>
					Point (Lat, Long): 
					<span id="latlngspan" style="font-weight:bold;"></span>
					<span style="float:right;margin-right:50px;">
						<input type="hidden" name="interface" value="<?php echo $interface; ?>" />
						<input type="submit" name="addcoords" value="Submit Coordinates" />
					</span>
					<span style="float:right;margin-right:10px;">
						<select name="tid">
							<option value="0">Taxon Filter (optional)</option>
							<?php 
							$taxaArr = $dynClManager->getFilterTaxa();
							foreach($taxaArr as $k => $sciname){
								echo "<option value='".$k."' ".($k==$tid?"SELECTED":"").">".$sciname."</option>";
							}
							?>
						</select>
					</span> 
					<input type="hidden" id="radius" name="radius" value="" />
					<input type="hidden" id="latbox" name="lat" value="" />
					<input type="hidden" id="lngbox" name="lng" value="" />
				</div>
				<div style="display:none;">
					Radius: <input type="text" id="radiustemp"  name="radiustemp" size="5" onchange="updateRadius();" /> 
					<select id="radiusunits" name="radiusunits" onchange="updateRadius();">
						<option value="mi">Miles</option>
						<option value="km">Kilometers</option>
					</select>
				</div>
			</form>
		</div>
	    <div id='map' style='width: 700px; height: 600px;clear:both;'></div>
	<?php
	 	include_once($serverRoot.'/footer.php');
	?>

</body>
</html>
