# See ${SYMBIOTA_ROOT}/docker/config/*.php for variable descriptions

database:
  host: localhost
  port: 3306
  name: symbiota
  users:
    readonly:
      username: readonly
      password: password
    readwrite:
      username: readonly
      password: password

symbini:
  core:
    default_lang: 'en'
    proj_id: 1
    cat_id: 0
    page_title: Symbiota
    tid_focus:
    admin_email: somebody@somehost.com
    portal_guid: 21013e21595742f2bb705c0e62cfeff0
    security_key: bcb6c85831a5480496b94d2a21c93fcb
  data:
    path_symbiota_root: /var/www/symbiota
    url_path_root: /
    url_path_images: /image
    image_domain:
    path_image_iplant:
  nlp:
    lbcc_activated: 0
    salix_activated: 0
  modules:
    occurrence: 1
    flora: 1
    key: 1
    tracking: 0
    filtered_push: 0
  geoserver:
    url:
    record_layer:
  solr:
    url:
    full_import_interval: 24
  gbif:
    username:
    password:
    ocr_key:
  misc:
    google:
      analytics_key:
      map_key:
      map_zoom: 6
      boundaries:
    spacial:
      initial_center:
      initial_zoom:
    taxon_profile:
      map_center:
      map_zoom:
    recaptcha:
      public_key:
      private_key:
    georeference_political_divisions: false
    eol_key:
    taxonomic_authorities:
      COL:
      WoRMS:
    quick_host_entry_active: 0
    portal_taxa_desc:
    glossary_export_banner:
    dyn_checklist_radius: 10
    display_common_names: 1
    exsiccati: 0
    checklist_fg_export: 0
    fieldguide:
      active: 0
      api_key:
    genbank_tool_path:
    geolocate_toolkit: 0
  navigation:
    checklists_menu: 0
    collections:
      index_menu: 0
      harvest_params_menu: 0
      list_menu: 0
      checklist_menu: 0
      download_menu: 0
      maps_menu: 0
      loans_index_menu: 0
    ident:
      key_menu: 0
      chardeficit_menu: 0
      mass_update_menu: 0
      editor_menu: 0
    taxa:
      index_menu: 0
      admin_tpeditor_menu: 0
    glossary_index_banner: 0
    agents:
      index_menu: true
      index_crumbs: []

header:
  header_image: defaultheader.jpg

footer:
  footer_html: <h4>An example footer</h4>
