swagger: '2.0'

info:
  version: "0.0.1"
  title: Agent Authority
  
paths:
  /agents:
    get:
      description: |
        Query for and list agents matching one or more of the provided parameters. 
        Parameter values may be provided as a string value or a regex
      parameters:
        -
          name: familyname
          in: query
          description: Collector's family name
          required: false
          type: string
        -
          name: firstname
          in: query
          description: Collector's first name
          required: false
          type: string
        -
          name: middlename
          in: query
          description: Collector's middle name
          required: false
          type: string
        -
          name: namestring
          in: query
          description: Collector's full name
          required: false
          type: string
        -
          name: yearofbirth
          in: query
          description: Collector's year of birth
          required: false
          type: string
        -
          name: yearofdeath
          in: query
          description: Collector's year of death
          required: false
          type: string
        -
          name: variantname
          in: query
          description: Search against any variant names
          required: false
          type: string
          
      responses:
        200:
          description: Successful response
          schema: 
            $ref: '#/definitions/AgentList'
          
  /agent:
    get:
      description: |
        Query agent by uuid
      parameters:
        -
          name: uuid
          in: query
          description: Collector uuid
          required: true
          type: string
          
      responses:
        200:
          description: Successful response
          schema: 
            $ref: '#/definitions/AgentList'

definitions:

  AgentList:
    title: AgentList
    type: array
    items:
      $ref: '#/definitions/Agent'
      
  Agent:
    title: Agent
    type: object
    properties:
      id:
        type: integer
      type:
        type: string
        pattern: (Team|Individual|Organization)
      prefix:
        type: string
      firstname:
        type: string
      middlename:
        type: string
      familyname:
        type: string
      suffix:
        type: string
      namestring:
        type: string
      yearofbirth:
        type: string
      yearofdeath:
        type: string
      matchednamevariant:
        type: string
      score:
        type: number
        format: double