<?php
include_once($SERVER_ROOT.'/content/lang/collections/harvestparams.'.$LANG_TAG.'.php');

$SEARCHTEXT = array();

//Search Parameter Label text: variables and values for search parameter labels
$SEARCHTEXT['PAGE_TITLE'] = $LANG['PAGE_TITLE'];
$SEARCHTEXT['PAGE_HEADER'] = $LANG['PAGE_HEADER'];
$SEARCHTEXT['GENERAL_TEXT_1'] = $LANG['GENERAL_TEXT_1'];
$SEARCHTEXT['TAXON_HEADER'] = $LANG['TAXON_HEADER'];
$SEARCHTEXT['TAXON_INPUT'] = $LANG['TAXON_INPUT'];
$SEARCHTEXT['GENERAL_TEXT_2'] = $LANG['GENERAL_TEXT_2'];
$SEARCHTEXT['GENERAL_TEXT_2_MAP'] = $LANG['GENERAL_TEXT_2_MAP'];
$SEARCHTEXT['SELECT_1-1'] = $LANG['SELECT_1-1'];
$SEARCHTEXT['SELECT_1-2'] = $LANG['SELECT_1-2'];
$SEARCHTEXT['SELECT_1-3'] = $LANG['SELECT_1-3'];
$SEARCHTEXT['SELECT_1-4'] = $LANG['SELECT_1-4'];
$SEARCHTEXT['SELECT_1-5'] = $LANG['SELECT_1-5'];
$SEARCHTEXT['TITLE_TEXT_1'] = $LANG['TITLE_TEXT_1'];
$SEARCHTEXT['LOCALITY_HEADER'] = $LANG['LOCALITY_HEADER'];
$SEARCHTEXT['COUNTRY_INPUT'] = $LANG['COUNTRY_INPUT'];
$SEARCHTEXT['STATE_INPUT'] = $LANG['STATE_INPUT'];
$SEARCHTEXT['COUNTY_INPUT'] = $LANG['COUNTY_INPUT'];
$SEARCHTEXT['LOCALITY_INPUT'] = $LANG['LOCALITY_INPUT'];
$SEARCHTEXT['ELEV_INPUT_1'] = $LANG['ELEV_INPUT_1'];
$SEARCHTEXT['ELEV_INPUT_2'] = $LANG['ELEV_INPUT_2'];
$SEARCHTEXT['ASSOC_HOST_INPUT'] = $LANG['ASSOC_HOST_INPUT'];
$SEARCHTEXT['LAT_LNG_HEADER'] = $LANG['LAT_LNG_HEADER'];
$SEARCHTEXT['LL_BOUND_TEXT'] = $LANG['LL_BOUND_TEXT'];
$SEARCHTEXT['LL_BOUND_NLAT'] = $LANG['LL_BOUND_NLAT'];
$SEARCHTEXT['LL_BOUND_SLAT'] = $LANG['LL_BOUND_SLAT'];
$SEARCHTEXT['LL_BOUND_WLNG'] = $LANG['LL_BOUND_WLNG'];
$SEARCHTEXT['LL_BOUND_ELNG'] = $LANG['LL_BOUND_ELNG'];
$SEARCHTEXT['LL_N_SYMB'] = $LANG['LL_N_SYMB'];
$SEARCHTEXT['LL_S_SYMB'] = $LANG['LL_S_SYMB'];
$SEARCHTEXT['LL_W_SYMB'] = $LANG['LL_W_SYMB'];
$SEARCHTEXT['LL_E_SYMB'] = $LANG['LL_E_SYMB'];
$SEARCHTEXT['LL_P-RADIUS_TEXT'] = $LANG['LL_P-RADIUS_TEXT'];
$SEARCHTEXT['LL_P-RADIUS_LAT'] = $LANG['LL_P-RADIUS_LAT'];
$SEARCHTEXT['LL_P-RADIUS_LNG'] = $LANG['LL_P-RADIUS_LNG'];
$SEARCHTEXT['LL_P-RADIUS_RADIUS'] = $LANG['LL_P-RADIUS_RADIUS'];
$SEARCHTEXT['LL_P-RADIUS_KM'] = $LANG['LL_P-RADIUS_KM'];
$SEARCHTEXT['LL_P-RADIUS_MI'] = $LANG['LL_P-RADIUS_MI'];
$SEARCHTEXT['LL_P-RADIUS_TITLE_1'] = $LANG['LL_P-RADIUS_TITLE_1'];
$SEARCHTEXT['COLLECTOR_HEADER'] = $LANG['COLLECTOR_HEADER'];
$SEARCHTEXT['COLLECTOR_LASTNAME'] = $LANG['COLLECTOR_LASTNAME'];
$SEARCHTEXT['TITLE_TEXT_2'] = $LANG['TITLE_TEXT_2'];
$SEARCHTEXT['COLLECTOR_NUMBER'] = $LANG['COLLECTOR_NUMBER'];
$SEARCHTEXT['COLLECTOR_DATE'] = $LANG['COLLECTOR_DATE'];
$SEARCHTEXT['TITLE_TEXT_3'] = $LANG['TITLE_TEXT_3'];
$SEARCHTEXT['TITLE_TEXT_4'] = $LANG['TITLE_TEXT_4'];
$SEARCHTEXT['SPECIMEN_HEADER'] = $LANG['SPECIMEN_HEADER'];
$SEARCHTEXT['CATALOG_NUMBER'] = $LANG['CATALOG_NUMBER'];
$SEARCHTEXT['INCLUDE_OTHER_CATNUM'] = $LANG['INCLUDE_OTHER_CATNUM'];
$SEARCHTEXT['OTHER_CATNUM'] = $LANG['OTHER_CATNUM'];
$SEARCHTEXT['TYPE'] = $LANG['TYPE'];
$SEARCHTEXT['HAS_IMAGE'] = $LANG['HAS_IMAGE'];
$SEARCHTEXT['HAS_GENETIC'] = $LANG['HAS_GENETIC'];

//Following used in mapboundingbox.php
$SEARCHTEXT['MBB_TITLE'] = $LANG['MBB_TITLE'];
$SEARCHTEXT['MBB_INSTRUCTIONS'] = $LANG['MBB_INSTRUCTIONS'];
$SEARCHTEXT['MBB_NORTHERN'] = $LANG['MBB_NORTHERN'];
$SEARCHTEXT['MBB_EASTERN'] = $LANG['MBB_EASTERN'];
$SEARCHTEXT['MBB_SOUTHERN'] = $LANG['MBB_SOUTHERN'];
$SEARCHTEXT['MBB_WESTERN'] = $LANG['MBB_WESTERN'];

//Following used in mappointradius.php
$SEARCHTEXT['MPR_TITLE'] = $LANG['MPR_TITLE'];
$SEARCHTEXT['MPR_INSTRUCTIONS'] = $LANG['MPR_INSTRUCTIONS'];
$SEARCHTEXT['MPR_LAT'] = $LANG['MPR_LAT'];
$SEARCHTEXT['MPR_LNG'] = $LANG['MPR_LNG'];
$SEARCHTEXT['SUBMIT'] = $LANG['SUBMIT'];

?>