<?php
//Search Parameter Label text: uncomment variables and values to modify search parameter labels
//$SEARCHTEXT['PAGE_TITLE'] = '';
//$SEARCHTEXT['PAGE_HEADER'] = '';
//$SEARCHTEXT['GENERAL_TEXT_1'] = '';
//$SEARCHTEXT['TAXON_HEADER'] = '';
//$SEARCHTEXT['TAXON_INPUT'] = '';
//$SEARCHTEXT['GENERAL_TEXT_2'] = '';
//$SEARCHTEXT['GENERAL_TEXT_2_MAP'] = '';
//$SEARCHTEXT['SELECT_1-1'] = '';
//$SEARCHTEXT['SELECT_1-2'] = '';
//$SEARCHTEXT['SELECT_1-3'] = '';
//$SEARCHTEXT['SELECT_1-4'] = '';
//$SEARCHTEXT['SELECT_1-5'] = '';
//$SEARCHTEXT['TITLE_TEXT_1'] = '';
//$SEARCHTEXT['LOCALITY_HEADER'] = '';
//$SEARCHTEXT['COUNTRY_INPUT'] = '';
//$SEARCHTEXT['STATE_INPUT'] = '';
//$SEARCHTEXT['COUNTY_INPUT'] = '';
//$SEARCHTEXT['LOCALITY_INPUT'] = '';
//$SEARCHTEXT['ELEV_INPUT_1'] = '';
//$SEARCHTEXT['ELEV_INPUT_2'] = '';
//$SEARCHTEXT['ASSOC_HOST_INPUT'] = '';
//$SEARCHTEXT['LAT_LNG_HEADER'] = '';
//$SEARCHTEXT['LL_BOUND_TEXT'] = '';
//$SEARCHTEXT['LL_BOUND_NLAT'] = '';
//$SEARCHTEXT['LL_BOUND_SLAT'] = '';
//$SEARCHTEXT['LL_BOUND_WLNG'] = '';
//$SEARCHTEXT['LL_BOUND_ELNG'] = '';
//$SEARCHTEXT['LL_N_SYMB'] = '';
//$SEARCHTEXT['LL_S_SYMB'] = '';
//$SEARCHTEXT['LL_W_SYMB'] = '';
//$SEARCHTEXT['LL_E_SYMB'] = '';
//$SEARCHTEXT['LL_P-RADIUS_TEXT'] = '';
//$SEARCHTEXT['LL_P-RADIUS_LAT'] = '';
//$SEARCHTEXT['LL_P-RADIUS_LNG'] = '';
//$SEARCHTEXT['LL_P-RADIUS_RADIUS'] = '';
//$SEARCHTEXT['LL_P-RADIUS_KM'] = '';
//$SEARCHTEXT['LL_P-RADIUS_MI'] = '';
//$SEARCHTEXT['LL_P-RADIUS_TITLE_1'] = '';
//$SEARCHTEXT['COLLECTOR_HEADER'] = '';
//$SEARCHTEXT['COLLECTOR_LASTNAME'] = '';
//$SEARCHTEXT['TITLE_TEXT_2'] = '';
//$SEARCHTEXT['COLLECTOR_NUMBER'] = '';
//$SEARCHTEXT['COLLECTOR_DATE'] = '';
//$SEARCHTEXT['TITLE_TEXT_3'] = '';
//$SEARCHTEXT['TITLE_TEXT_4'] = '';
//$SEARCHTEXT['SPECIMEN_HEADER'] = '';
$SEARCHTEXT['CATALOG_NUMBER'] = 'Accession Number:';
$SEARCHTEXT['INCLUDE_OTHER_CATNUM'] = 'Include barcode numbers and GUIDs';
$SEARCHTEXT['OTHER_CATNUM'] = 'Barcode #:';
//$SEARCHTEXT['TYPE'] = '';
//$SEARCHTEXT['HAS_IMAGE'] = '';
//$SEARCHTEXT['HAS_GENETIC'] = '';

//Following used in mapboundingbox.php
//$SEARCHTEXT['MBB_TITLE'] = '';
//$SEARCHTEXT['MBB_INSTRUCTIONS'] = '';
//$SEARCHTEXT['MBB_NORTHERN'] = '';
//$SEARCHTEXT['MBB_EASTERN'] = '';
//$SEARCHTEXT['MBB_SOUTHERN'] = '';
//$SEARCHTEXT['MBB_WESTERN'] = '';

//Following used in mappointradius.php
//$SEARCHTEXT['MPR_TITLE'] = '';
//$SEARCHTEXT['MPR_INSTRUCTIONS'] = '';
//$SEARCHTEXT['MPR_LAT'] = '';
//$SEARCHTEXT['MPR_LNG'] = '';
//$SEARCHTEXT['SUBMIT'] = '';

?>